name: videogs
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-11.8.0
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.12.2
  - cuda-cccl=11.8.89
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.8.89
  - cuda-gdb=11.8.86
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.8.86
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.8.87
  - cuda-profiler-api=11.8.86
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-visual-tools=11.8.0
  - expat=2.7.3
  - gcc_impl_linux-64=11.4.0
  - gcc_linux-64=11.4.0
  - gds-tools=1.4.0.31
  - gettext=0.21.0
  - glew=2.2.0
  - gxx_impl_linux-64=11.4.0
  - gxx_linux-64=11.4.0
  - icu=73.1
  - jansson=2.14
  - kernel-headers_linux-64=3.10.0
  - ld_impl_linux-64=2.40
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcurl=8.16.0
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-devel_linux-64=11.4.0
  - libgcc-ng=15.2.0
  - libgl=1.7.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libnghttp2=1.67.1
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libopengl=1.7.0
  - libsanitizer=11.4.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=11.4.0
  - libstdcxx-ng=15.2.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - ncurses=6.5
  - nsight-compute=2022.3.0.22
  - openssl=3.6.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.9.25
  - readline=8.3
  - rhash=1.4.6
  - setuptools=80.9.0
  - sqlite=3.51.0
  - sysroot_linux-64=2.17
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cmake==3.25.0
      - comm==0.2.3
      - commentjson==0.9.0
      - configargparse==1.7.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==3.3.0
      - decorator==5.2.1
      - diff-gaussian-rasterization==0.0.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flask==3.1.2
      - fonttools==4.60.2
      - grpcio==1.76.0
      - idna==3.4
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.7
      - lark-parser==0.7.8
      - lit==15.0.7
      - markdown==3.9
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - narwhals==2.13.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==1.26.4
      - open3d==0.19.0
      - opencv-python==4.9.0.80
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plotly==6.5.0
      - plyfile==1.1.3
      - prompt-toolkit==3.0.52
      - protobuf==6.33.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==3.0.1
      - pygments==2.19.2
      - pymeshlab==2025.7
      - pyparsing==3.2.5
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.28.1
      - retrying==1.4.2
      - rpds-py==0.27.1
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - simple-knn==0.0.0
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tinycudann==2.0
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.10.1
      - triton==2.0.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==1.26.13
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
